# Make data

```{r}
library(tidyverse)
df_3d <-
  data_frame(x = rep(1:20, each = 20),
             y = rep(1:20, times = 20),
             z1 = x + y + 0.5 * x * y,
             z2 = 5 * x + 3 * y - 0.5 * x * y) %>%
  tidyr::gather(group, z, -x, -y)

df_3d_group1 <-
  df_3d %>%
  filter(group == "z1")

df_3d_group2 <-
  df_3d %>%
  filter(group == "z2")
```

```{r}
df_3d_group1 %>% str
```

```{r}
df_3d_group2 %>% str
```


# Make graph

```{r}
library(rgl)

plot3d(df_3d_group1$x, df_3d_group1$y, df_3d_group1$z, zlim = c(-50, 250))
plot3d(df_3d_group2$x, df_3d_group2$y, df_3d_group2$z, col = "red", zlim = c(-50, 250))
rglwidget()
```

# Add surfaces

```{r}
library(akima)

surf1 <- interp(df_3d_group1$x, df_3d_group1$y, df_3d_group1$z)
surf2 <- interp(df_3d_group2$x, df_3d_group2$y, df_3d_group2$z)

plot3d(df_3d_group1$x, df_3d_group1$y, df_3d_group1$z, col = "grey10", zlim = c(-50, 250))
plot3d(df_3d_group2$x, df_3d_group2$y, df_3d_group2$z, col = "red", zlim = c(-50, 250))

surface3d(surf1$x, surf1$y, surf1$z, col = "grey", alpha = .3)
surface3d(surf2$x, surf2$y, surf2$z, col = "red", alpha = .3)
rglwidget()
```

